// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CreateRoomC2S.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from CreateRoomC2S.proto</summary>
public static partial class CreateRoomC2SReflection {

  #region Descriptor
  /// <summary>File descriptor for CreateRoomC2S.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CreateRoomC2SReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNDcmVhdGVSb29tQzJTLnByb3RvGg5Sb29tSW5mby5wcm90byI+Cg1DcmVh",
          "dGVSb29tQzJTEhAKCHJvb21TaXplGAEgASgFEhsKCHJvb21UeXBlGAIgASgO",
          "MgkuUm9vbVR5cGViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::RoomInfoReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::CreateRoomC2S), global::CreateRoomC2S.Parser, new[]{ "RoomSize", "RoomType" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class CreateRoomC2S : pb::IMessage<CreateRoomC2S> {
  private static readonly pb::MessageParser<CreateRoomC2S> _parser = new pb::MessageParser<CreateRoomC2S>(() => new CreateRoomC2S());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<CreateRoomC2S> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CreateRoomC2SReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CreateRoomC2S() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CreateRoomC2S(CreateRoomC2S other) : this() {
    roomSize_ = other.roomSize_;
    roomType_ = other.roomType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CreateRoomC2S Clone() {
    return new CreateRoomC2S(this);
  }

  /// <summary>Field number for the "roomSize" field.</summary>
  public const int RoomSizeFieldNumber = 1;
  private int roomSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RoomSize {
    get { return roomSize_; }
    set {
      roomSize_ = value;
    }
  }

  /// <summary>Field number for the "roomType" field.</summary>
  public const int RoomTypeFieldNumber = 2;
  private global::RoomType roomType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RoomType RoomType {
    get { return roomType_; }
    set {
      roomType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as CreateRoomC2S);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(CreateRoomC2S other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoomSize != other.RoomSize) return false;
    if (RoomType != other.RoomType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (RoomSize != 0) hash ^= RoomSize.GetHashCode();
    if (RoomType != 0) hash ^= RoomType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (RoomSize != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RoomSize);
    }
    if (RoomType != 0) {
      output.WriteRawTag(16);
      output.WriteEnum((int) RoomType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (RoomSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomSize);
    }
    if (RoomType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RoomType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(CreateRoomC2S other) {
    if (other == null) {
      return;
    }
    if (other.RoomSize != 0) {
      RoomSize = other.RoomSize;
    }
    if (other.RoomType != 0) {
      RoomType = other.RoomType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RoomSize = input.ReadInt32();
          break;
        }
        case 16: {
          roomType_ = (global::RoomType) input.ReadEnum();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
