// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ErrorType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ErrorType.proto</summary>
public static partial class ErrorTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for ErrorType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9FcnJvclR5cGUucHJvdG8qawoJRXJyb3JUeXBlEg4KCk5VTExfRVJST1IQ",
          "ABIYChRMT0dJTl9XUk9OR19QQVNTV09SRBABEhcKE0xPR0lOX05PTkVfVVNF",
          "Uk5BTUUQAhIbChdSRUdJU1RFUl9FWElTVF9VU0VSTkFNRRADYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ErrorType), }, null));
  }
  #endregion

}
#region Enums
public enum ErrorType {
  /// <summary>
  ///无错误
  /// </summary>
  [pbr::OriginalName("NULL_ERROR")] NullError = 0,
  /// <summary>
  ///登录时密码错误
  /// </summary>
  [pbr::OriginalName("LOGIN_WRONG_PASSWORD")] LoginWrongPassword = 1,
  /// <summary>
  ///登录时用户名不存在
  /// </summary>
  [pbr::OriginalName("LOGIN_NONE_USERNAME")] LoginNoneUsername = 2,
  /// <summary>
  ///注册时用户名已存在
  /// </summary>
  [pbr::OriginalName("REGISTER_EXIST_USERNAME")] RegisterExistUsername = 3,
}

#endregion


#endregion Designer generated code
