// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RegisterS2C.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from RegisterS2C.proto</summary>
public static partial class RegisterS2CReflection {

  #region Descriptor
  /// <summary>File descriptor for RegisterS2C.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RegisterS2CReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFSZWdpc3RlclMyQy5wcm90byKEAQoLUmVnaXN0ZXJTMkMSDQoFZXJyb3IY",
          "ASABKAUSLQoLcmVnaXN0ZXJSZXQYAiABKA4yGC5SZWdpc3RlclMyQy5SZWdp",
          "c3RlclJldCI3CgtSZWdpc3RlclJldBIUChBSRUdJU1RFUl9TVUNDRVNTEAAS",
          "EgoORVhJU1RfVVNFUk5BTUUQAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RegisterS2C), global::RegisterS2C.Parser, new[]{ "Error", "RegisterRet" }, null, new[]{ typeof(global::RegisterS2C.Types.RegisterRet) }, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RegisterS2C : pb::IMessage<RegisterS2C> {
  private static readonly pb::MessageParser<RegisterS2C> _parser = new pb::MessageParser<RegisterS2C>(() => new RegisterS2C());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RegisterS2C> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RegisterS2CReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RegisterS2C() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RegisterS2C(RegisterS2C other) : this() {
    error_ = other.error_;
    registerRet_ = other.registerRet_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RegisterS2C Clone() {
    return new RegisterS2C(this);
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 1;
  private int error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  /// <summary>Field number for the "registerRet" field.</summary>
  public const int RegisterRetFieldNumber = 2;
  private global::RegisterS2C.Types.RegisterRet registerRet_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::RegisterS2C.Types.RegisterRet RegisterRet {
    get { return registerRet_; }
    set {
      registerRet_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RegisterS2C);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RegisterS2C other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Error != other.Error) return false;
    if (RegisterRet != other.RegisterRet) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Error != 0) hash ^= Error.GetHashCode();
    if (RegisterRet != 0) hash ^= RegisterRet.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Error != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Error);
    }
    if (RegisterRet != 0) {
      output.WriteRawTag(16);
      output.WriteEnum((int) RegisterRet);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Error != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
    }
    if (RegisterRet != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RegisterRet);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RegisterS2C other) {
    if (other == null) {
      return;
    }
    if (other.Error != 0) {
      Error = other.Error;
    }
    if (other.RegisterRet != 0) {
      RegisterRet = other.RegisterRet;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Error = input.ReadInt32();
          break;
        }
        case 16: {
          registerRet_ = (global::RegisterS2C.Types.RegisterRet) input.ReadEnum();
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the RegisterS2C message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum RegisterRet {
      /// <summary>
      ///注册成功
      /// </summary>
      [pbr::OriginalName("REGISTER_SUCCESS")] RegisterSuccess = 0,
      /// <summary>
      ///用户名已存在
      /// </summary>
      [pbr::OriginalName("EXIST_USERNAME")] ExistUsername = 1,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
